name: Unit Tests

on: [push, pull_request]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting unit test"
      - uses: actions/checkout@v4
      - run: npm install && npm run test:ci
      - run: echo "Finished unit test"
